---
apiVersion: v1
kind: Namespace
metadata:
  name: freescout

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: freescout-mariadb-data
  namespace: freescout
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: longhorn

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: freescout-data
  namespace: freescout
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: longhorn

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: freescout-logs
  namespace: freescout
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: longhorn

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: freescout-db
  namespace: freescout
spec:
  replicas: 1
  selector:
    matchLabels:
      app: freescout-db
  template:
    metadata:
      labels:
        app: freescout-db
    spec:
      tolerations:
      - key: "node-role.kubernetes.io/control-plane"
        operator: "Exists"
        effect: "NoSchedule"
      - key: "node-role.kubernetes.io/master"
        operator: "Exists"
        effect: "NoSchedule"
      containers:
      - name: mariadb
        image: tiredofit/mariadb:latest
        ports:
        - containerPort: 3306
        env:
        - name: ROOT_PASS
          valueFrom:
            secretKeyRef:
              name: freescout-secrets
              key: db-root-password
        - name: DB_NAME
          value: freescout
        - name: DB_USER
          value: freescout
        - name: DB_PASS
          valueFrom:
            secretKeyRef:
              name: freescout-secrets
              key: db-password
        - name: CONTAINER_NAME
          value: freescout-db
        volumeMounts:
        - name: mariadb-data
          mountPath: /var/lib/mysql
        resources:
          requests:
            cpu: 250m
            memory: 512Mi
          limits:
            cpu: 1000m
            memory: 2Gi
        livenessProbe:
          exec:
            command:
            - mysqladmin
            - ping
            - -h
            - localhost
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          exec:
            command:
            - mysqladmin
            - ping
            - -h
            - localhost
          initialDelaySeconds: 5
          periodSeconds: 5
      volumes:
      - name: mariadb-data
        persistentVolumeClaim:
          claimName: freescout-mariadb-data

---
apiVersion: v1
kind: Service
metadata:
  name: freescout-db
  namespace: freescout
spec:
  selector:
    app: freescout-db
  ports:
  - port: 3306

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: freescout-app
  namespace: freescout
spec:
  replicas: 1
  selector:
    matchLabels:
      app: freescout-app
  template:
    metadata:
      labels:
        app: freescout-app
    spec:
      tolerations:
      - key: "node-role.kubernetes.io/control-plane"
        operator: "Exists"
        effect: "NoSchedule"
      - key: "node-role.kubernetes.io/master"
        operator: "Exists"
        effect: "NoSchedule"
      initContainers:
      - name: wait-for-db
        image: mariadb:10.6
        command:
        - sh
        - -c
        - |
          until mysqladmin ping -h freescout-db --silent; do
            echo "Waiting for MariaDB..."
            sleep 5
          done
      containers:
      - name: freescout
        image: tiredofit/freescout:latest
        ports:
        - containerPort: 80
        env:
        - name: CONTAINER_NAME
          value: freescout-app
        - name: DB_HOST
          value: freescout-db
        - name: DB_NAME
          value: freescout
        - name: DB_USER
          value: freescout
        - name: DB_PASS
          valueFrom:
            secretKeyRef:
              name: freescout-secrets
              key: db-password
        - name: SITE_URL
          value: "https://help.starnix.net"
        - name: APP_CLOUDFLARE_IS_USED
          value: "true"
        - name: ADMIN_EMAIL
          value: "admin@starnix.net"
        - name: ADMIN_PASS
          valueFrom:
            secretKeyRef:
              name: freescout-secrets
              key: admin-password
        - name: ENABLE_SSL_PROXY
          value: "TRUE"
        - name: DISPLAY_ERRORS
          value: "FALSE"
        - name: TIMEZONE
          value: "America/Chicago"
        volumeMounts:
        - name: freescout-data
          mountPath: /data
        - name: freescout-logs
          mountPath: /www/logs
        resources:
          requests:
            cpu: 300m
            memory: 512Mi
          limits:
            cpu: 1000m
            memory: 2Gi
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 120
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 60
          periodSeconds: 10
          timeoutSeconds: 5
      volumes:
      - name: freescout-data
        persistentVolumeClaim:
          claimName: freescout-data
      - name: freescout-logs
        persistentVolumeClaim:
          claimName: freescout-logs

---
apiVersion: v1
kind: Service
metadata:
  name: freescout-app
  namespace: freescout
spec:
  selector:
    app: freescout-app
  ports:
  - port: 80

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: freescout-ingress
  namespace: freescout
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-production"
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
spec:
  ingressClassName: traefik
  tls:
  - hosts:
    - freescout.starnix.net
    secretName: freescout-tls
  rules:
  - host: freescout.starnix.net
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: freescout-app
            port:
              number: 80

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: freescout-hpa
  namespace: freescout
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: freescout-app
  minReplicas: 1
  maxReplicas: 3
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
