apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn-helm
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: default
  source:
    repoURL: https://charts.longhorn.io
    chart: longhorn
    targetRevision: 1.6.2
    helm:
      releaseName: longhorn
      values: |
        persistence:
          defaultClassReplicaCount: 3
          recurringJobSelector:
            enable: true
            jobList: '[{"name":"daily-backup","isGroup":false},{"name":"hourly-snapshot","isGroup":false}]'
        defaultSettings:
          backupTarget: s3://longhorn-backup@us-east-1/
          backupTargetCredentialSecret: minio-secret
        tolerations:
          - key: "node-role.kubernetes.io/control-plane"
            operator: "Exists"
            effect: "NoSchedule"
  destination:
    server: https://kubernetes.default.svc
    namespace: longhorn-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
