apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-helm
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  project: default
  source:
    repoURL: https://argoproj.github.io/argo-helm
    chart: argo-cd
    targetRevision: 7.7.20
    helm:
      releaseName: argocd
      values: |
        global:
          tolerations:
            - key: "node-role.kubernetes.io/control-plane"
              operator: "Exists"
              effect: "NoSchedule"

        server:
          ingress:
            enabled: false  # We manage this separately via Traefik

          config:
            repositories: |
              - type: git
                url: https://github.com/usenix17/ArgoCD.git

        configs:
          cm:
            url: https://argocd.starnix.net
            oidc.config: |
              name: Starnix
              issuer: https://auth.starnix.net/application/o/argocd/
              clientID: hMxnyA6KclvS6xyI7OUj1MewppIXYFAI8EV84xNY
              clientSecret: $oidc.authentik.clientSecret
              requestedScopes:
                - openid
                - profile
                - email
          rbac:
            policy.default: role:admin
          params:
            server.insecure: true  # TLS termination handled by Traefik

        applicationSet:
          enabled: true

        notifications:
          enabled: true
          cm:
            service.webhook.apprise: |
              url: http://apprise.apprise.svc:8000/notify/argocd
              headers:
              - name: Content-Type
                value: application/json
            template.app-sync-succeeded: |
              webhook:
                apprise:
                  method: POST
                  body: |
                    {
                      "title": "{{.app.metadata.name}}",
                      "body": "✅ **{{.app.metadata.name}}** synced successfully.\nRevision: `{{.app.status.sync.revision | trunc 7}}`\nHealth: {{.app.status.health.status}}"
                    }
            template.app-sync-failed: |
              webhook:
                apprise:
                  method: POST
                  body: |
                    {
                      "title": "{{.app.metadata.name}}",
                      "body": "❌ **{{.app.metadata.name}}** sync failed.\n{{.app.status.operationState.message}}"
                    }
            template.app-health-degraded: |
              webhook:
                apprise:
                  method: POST
                  body: |
                    {
                      "title": "{{.app.metadata.name}}",
                      "body": "⚠️ **{{.app.metadata.name}}** health is **Degraded**."
                    }
            trigger.on-sync-succeeded: |
              - when: app.status.operationState.phase in ['Succeeded']
                send: [app-sync-succeeded]
            trigger.on-sync-failed: |
              - when: app.status.operationState.phase in ['Error', 'Failed']
                send: [app-sync-failed]
            trigger.on-health-degraded: |
              - when: app.status.health.status == 'Degraded'
                send: [app-health-degraded]
            defaultTriggers: |
              - on-sync-succeeded
              - on-sync-failed
              - on-health-degraded
            subscriptions: |
              - recipients:
                - apprise:
                triggers:
                - on-sync-succeeded
                - on-sync-failed
                - on-health-degraded
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  ignoreDifferences:
  - group: "*"
    kind: Secret
    name: argocd-initial-admin-secret
    jsonPointers:
    - /data
  - group: ""
    kind: ConfigMap
    name: argocd-notifications-cm
    jsonPointers:
    - /data
