---
apiVersion: v1
kind: Namespace
metadata:
  name: knot
  labels:
    name: knot
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: knot-config
  namespace: knot
data:
  knot.conf: |
    server:
        listen: 0.0.0.0@53
        rundir: /rundir

    log:
      - target: stderr
        any: info

    zone:
      - domain: starnix.net
        file: /etc/knot/zones/starnix.net.zone
        zonefile-load: whole
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: knot
  namespace: knot
  labels:
    app: knot
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: knot
  template:
    metadata:
      labels:
        app: knot
    spec:
      tolerations:
      - key: "node-role.kubernetes.io/control-plane"
        operator: "Exists"
        effect: "NoSchedule"
      - key: "node-role.kubernetes.io/master"
        operator: "Exists"
        effect: "NoSchedule"
      containers:
      - name: knot
        image: cznic/knot:3.4
        args: ["-c", "/etc/knot/knot.conf"]
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
            add:
            - NET_BIND_SERVICE
            - SETUID
            - SETGID
        ports:
        - containerPort: 53
          name: dns-tcp
          protocol: TCP
        - containerPort: 53
          name: dns-udp
          protocol: UDP
        resources:
          requests:
            cpu: 50m
            memory: 64Mi
          limits:
            cpu: 250m
            memory: 128Mi
        volumeMounts:
        - name: knot-config
          mountPath: /etc/knot/knot.conf
          subPath: knot.conf
        - name: knot-zone
          mountPath: /etc/knot/zones
        - name: rundir
          mountPath: /rundir
        livenessProbe:
          exec:
            command:
            - kdig
            - "@127.0.0.1"
            - starnix.net
            - SOA
            - +short
          initialDelaySeconds: 10
          periodSeconds: 30
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          exec:
            command:
            - knotc
            - -c
            - /etc/knot/knot.conf
            - status
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
      volumes:
      - name: knot-config
        configMap:
          name: knot-config
      - name: knot-zone
        configMap:
          name: knot-zone
      - name: rundir
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: knot
  namespace: knot
  labels:
    app: knot
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.7.211
  selector:
    app: knot
  ports:
  - name: dns-tcp
    port: 53
    targetPort: 53
    protocol: TCP
  - name: dns-udp
    port: 53
    targetPort: 53
    protocol: UDP
